lamp/authapp/urls.py
from django.urls import path

from authapp import views

app_name = 'authapp'
urlpatterns = [
    path('join/', views.join, name='join'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

lamp/lamp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from lamp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('mainapp.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lamp/mainapp/urls.py
from django.urls import path

from mainapp import views

app_name = 'mainapp'
urlpatterns = [
    path('<str:user>/boards/', views.boards, name='boards'),
    path('', views.main, name='main'),
    path('<str:board>/invite/', views.invite, name='invite'),
    path('<str:user>/<str:board>', views.board, name='board')
]

lamp/authapp/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models

lamp/mainapp/models.py
import random

from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class Board(models.Model):
    PROGRAMMING = 'Programming'
    DRAWING = 'Drawing'
    MUSIC = 'Music'

    CATEGORIES = (
        (PROGRAMMING, 'Programming'),
        (DRAWING, 'Drawing'),
        (MUSIC, 'Music'),
    )

    name = models.CharField(max_length=100, verbose_name="Board's name")
    type = models.CharField(max_length=15, choices=CATEGORIES, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=100, verbose_name="Board's token",
                             default=hash(str(name) + str(random.randint(1111111, 9999999))), unique=True)


class Column(models.Model):
    name = models.CharField(max_length=100, verbose_name="Column's name")
    board = models.ForeignKey(Board, on_delete=models.CASCADE)


class Task(models.Model):
    name = models.CharField(max_length=100, verbose_name="Board's name")
    description = models.TextField(max_length=500)
    column = models.ForeignKey(Column, on_delete=models.CASCADE)


class Image(models.Model):
    image = models.ImageField(verbose_name="Task's image")
    task = models.ForeignKey(Task, on_delete=models.CASCADE)


class Mark(models.Model):
    name = models.CharField(max_length=100, verbose_name="Mark's name")
    colour = models.CharField(max_length=50, verbose_name="Mark's colour")
    task = models.ForeignKey(Task, on_delete=models.CASCADE)


class TaskParticipate(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)


class Teammate(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

lamp/authapp/views.py
from django.contrib import auth
from django.shortcuts import render, redirect
from django.contrib.auth.models import User


# Create your views here.
from django.urls import reverse


def join(request):
    if request.method == 'POST':
        username = request.POST['username']
        name = request.POST['name']
        surname = request.POST['surname']
        email = request.POST['email']
        password = request.POST['password']
        User.objects.create_user(username, email, password,
                                 first_name=name, last_name=surname)
        return redirect(reverse('auth:login'))
    else:
        return render(request, 'authapp/join.html')

def login(request):
    print(request.user.is_authenticated)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            return redirect(reverse('main:main'))

    return render(request, 'authapp/login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

lamp/mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
import mainapp.utils as utils
from mainapp.models import Board, Teammate, Column, Task


def main(request):
    if request.user.is_authenticated == True:
        return redirect(reverse('main:boards', kwargs={'user': request.user.username}))
    else:
        return render(request, 'mainapp/main.html')


@login_required(login_url='/auth/login/')
def boards(request, user):
    if request.method == 'POST':
        name = request.POST['name']
        type = request.POST['type']

        user_ = User.objects.get(username=user)

        Board.objects.create(name=name, type=type,
                             author=user_, token=hash(name + user_.username))

        return redirect(reverse("main:main"))
    else:
        u = User.objects.get(username=user)
        if u == request.user:
            board = Board.objects.filter(author=u)
            teammate_boards = Teammate.objects.filter(user=request.user)

            return render(request, 'mainapp/boards.html', {'boards': board,
                                                           'teammate_boards': teammate_boards,
                                                           'user': u,
                                                           'board_types': Board.CATEGORIES})
        else:
            # TODO: create a 404 error
            raise Exception('Permission denied')


@login_required(login_url="auth/login/")
def invite(request, board):
    board_ = get_object_or_404(Board, token=board)

    if not len(Teammate.objects.filter(board=board_, user=request.user)):
        Teammate.objects.create(board=board_, user=request.user)

    return redirect(reverse('main:boards', kwargs={'user': request.user}))


def board(request, user, board):
    board_ = get_object_or_404(Board, author__username=user, id=board)
    users = Teammate.objects.filter(board=board_)
    if not (request.user == board_.author or utils.in_list(request.user, [user.user for user in users])):
        return redirect("/")

    data = []

    for column in Column.objects.filter(board=board_):
        c = {}
        c['id'] = column.id
        c['name'] = column.name
        c['tasks'] = Task.objects.filter(column=column)
        data.append(c)

    return render(request, 'mainapp/board.html', {'board': board_,
                                                  'data': data,
                                                  'users': users})

lamp/authapp/templates/authapp/join.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lamp - Sign up</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
{% include 'mainapp/includes/navbar.html' %}

<div class="container mt-5">

    <form action="{% url 'auth:join' %}" method="post">
                {% csrf_token %}

        <div class="form-group">
            <label>Enter username</label>
            <input type="text" name="username" class="form-control" placeholder="Enter username">
        </div>
        <div class="form-group">
            <label>Enter name</label>
            <input type="text" name="name" class="form-control" placeholder="Enter name">
        </div>
        <div class="form-group">
            <label>Enter surname</label>
            <input type="text" name="surname" class="form-control" placeholder="Enter surname">
        </div>
        <div class="form-group">
            <label>Enter email</label>
            <input type="email" name="email" class="form-control" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label>Enter password</label>
            <input type="password" name="password" class="form-control" placeholder="Enter password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>


</body>
</html>

lamp/authapp/templates/authapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lamp - Login</title>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
{% include 'mainapp/includes/navbar.html' %}


<div class="container mt-5">
    <form action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">Enter username</label>
            <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                   placeholder="Enter username">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Enter password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

</body>


</html>

lamp/mainapp/templates/mainapp/board.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lamp - {{ board.name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body style="width: 100%; min-height: 100%; background-size: cover; background-image: url('https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1537x1920/117d138c6be2845aadfd039c1b319cf7/photo-1580745389677-2b603a39011d.jpg')">
{% include 'mainapp/includes/navbar.html' %}

<div class="container-fluid mt-5">
    <h3>{{ board.name }} ({{ board.author.username }})</h3>
    <div class="boardTeammates">
        {% for user in users %}
            <div class="boardTeammate">
                {{ user.user.first_name }} {{ user.user.last_name }}
            </div>
        {% endfor %}
        <div class="boardTeammate">
            {{ board.author.first_name }} {{ board.author.last_name }}
        </div>
    </div>

    <div class="boardContent mt-3">
        {% for col in data %}
            <div class="columnWrapper">
                <div class="column">
                    <h4 class="columnHeader">{{ col.name }}</h4>
                    <div class="task">
                        {% for task in col.tasks %}
                            <div class="columnTask">
                                <p>{{ task.name }}</p>

                            </div>
                        {% endfor %}
                    </div>
                <div class="addTaskContainer">
                    <span class="addTask" data-id="{{ col.id }}">
                        + Add one more task
                    </span>
                    <form action="#" id="form-{{ col.id }}" style="display: none">
                        <div class="form-group">
                            <input type="text" name="name" placeholder="Column's name" class="form-control">
                        </div>
                        <button class="btn" style="color: white" type="submit">New column</button>
                    </form>
                </div>

                </div>
            </div>
        {% endfor %}
        <div class="columnWrapper">
            <div class="column">
                <h4 class="columnHeader">New column</h4>
                <form action="#">
                    <div class="form-group">
                        <input type="text" name="name" placeholder="Column's name" class="form-control">
                    </div>
                    <button class="btn" style="color: white" type="submit">New column</button>
                </form>
            </div>
        </div>
    </div>

</div>

<script>
    let tm = document.getElementsByClassName("boardTeammate");
    for (let user of tm) {
        let name = user.innerText.split(' ');
        console.log(name);
        let res = "";
        for (let n of name) {
            res += n[0]
        }
        console.log(res);

        user.innerText = res;
    }
</script>

<script>
    $(".addTask").click(function () {
       let id = $(this).data("id");
       $(`#form-${id}`).toggle();
    });
</script>

</body>
</html>

lamp/mainapp/templates/mainapp/boards.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lamp - Sign up</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
{% include 'mainapp/includes/navbar.html' %}

<div class="container mt-5">
    <h3 class="mb-5">Boards</h3>

    <button id="createBoardBtn" type="button" class="btn btn-primary">New Board</button>

    <div id="createBoard" class="mt-5 mb-5" style="display: none;">
        <h4>Create new board</h4>
        <form action="{% url 'main:boards' user.username %}" class="form-short" style=" border: none" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input name="name" class="form-control" type="text">

            </div>
            <div class="form-group">
                <select name="type" class="form-control">
                    {% for type in board_types %}
                        <option value="{{ type.0 }}">{{ type.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <input type="submit">
        </form>
    </div>


    <div class="boards mt-5">
        {% for board in boards %}
            <div class="board">
                <h4>
                    <a href="{% url 'main:board' board.author.username board.id %}">
                        {{ board.name }}

                    </a>
                </h4>
                <h6>
                    {{ board.type }}
                </h6>
                <p>
                    {{ board.author.username }}
                </p>
            </div>
        {% endfor %}

        <h3 class="mt-5">Your teams</h3>

        {% for teammate_board in teammate_boards %}
            <div class="board">
                <h4>
                    <a href="{% url 'main:board' teammate_board.board.author.username teammate_board.board.id %}">
                        {{ teammate_board.board.name }}

                    </a>
                </h4>
                <h6>
                    {{ teammate_board.board.type }}
                </h6>
                <p>
                    {{ teammate_board.board.author.username }}
                </p>
            </div>
        {% endfor %}
    </div>


</div>
<script>
    $("#createBoardBtn").click(function () {
        $("#createBoard").toggle();
    });
</script>

</body>
</html>

lamp/mainapp/templates/mainapp/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:#683a75!important;">
    <a class="navbar-brand" href="/">Lamp!</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'main:boards' user %}">Boards</a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'auth:logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'auth:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'auth:join' %}">Sign up</a>
            {% endif %}

        </div>
    </div>
</nav>

lamp/mainapp/templates/mainapp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lamp - Sign up</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
{% include 'mainapp/includes/navbar.html' %}

<div class="container mt-5">

    <div class="text-center">
        <h5>We are</h5>
        <h1>Lamp!</h1>
        <h6>Innovative tools for teams</h6>
    </div>

</div>


</body>
</html>